---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: slides
  label: Slide
  create: all
  match: "**/*"
  templates:
  - carousel
- type: directory
  path: blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: about
  label: About
  create: all
  match: "**/*"
  templates:
  - introduction-post
upload_dir: posts
public_path: https://res.cloudinary.com/quangdungandgreenpatio/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
