---
label: Product
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: images
  type: image_gallery
  config: {}
  label: Images
- name: imageOptimization
  type: text
  config:
    required: false
  label: Image Optimization
  default: q_auto:eco
  description: 'for example: q_auto:eco'
- name: product_type
  type: tag_list
  default: []
  label: Product Type
pages:
- products/2-seater-bench.md
- products/4-seats-regatta-dinning-set.md
- products/Coastal Adirondack Chair.md
- products/bench-hadia.md
- products/black-and-white-wicker-chair.md
- products/black-wicker-wooden-sofa.md
- products/blue-wash-bistro-set.md
- products/blue-wash-director-chair.md
- products/coastal-bench.md
- products/denim-wash-bistro-set.md
- products/flat-rope-woven-relaxing-chair.md
- products/grey-lutyens-garden-bench.md
- products/grey-park-bench-3-seater.md
- products/grey-wicker-chair.md
- products/luxury-ripcord-and-wooden-sofa.md
- products/painted-adirondack-chair-grey.md
- products/painted-adirondack-chair-red.md
- products/painted-ardirondack-chair-blue.md
- products/painted-ardirondack-chair-white.md
- products/rectangle-grey-wash-dinning-set.md
- products/relaxing-chair.md
- products/rose-bench.md
- products/sofa.md
- products/storage-bench-with-3-baskets.md
- products/sunbed.md
- products/white-bistro-set.md
- products/white-lutyens-garden-bench.md
- products/white-wooden-rocker-chair.md
- products/wicker-and-wooden-chair-with-cushion.md
- products/wicker-cushion-wood-chair.md
- products/wicker-relaxing-chair.md
- products/william-wicker-rocking-chair.md
- products/wooden-2-seater-garden-bench-with-under-seat-storage.md
- products/wooden-bench.md
