---
label: Product
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: images
  type: image_gallery
  config: {}
  label: Images
- name: imageOptimization
  type: text
  config:
    required: false
  label: Image Optimization
  default: q_auto:eco
  description: 'for example: q_auto:eco'
- name: category
  type: select
  default: []
  config:
    required: false
    options: []
    source:
      type: pages
      section: home-product-category
      file: 
      path: 
  label: Category
pages:
- products/wicker-cushion-wood-chair.md
- products/wooden-bench.md
