---
label: Product
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: category
  type: tag_list
  default: []
  label: Category
- name: images
  type: image_gallery
  config: {}
  label: Images
- name: imageOptimization
  type: text
  config:
    required: false
  label: Image Optimization
  default: q_auto:eco
  description: 'for example: q_auto:eco'
pages:
- products/wooden-bench.md
- products/wicker-cushion-wood-chair.md
