---
label: Product
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: images
  type: image_gallery
  config: {}
  label: Images
- name: imageOptimization
  type: text
  config:
    required: false
  label: Image Optimization
  default: q_auto:eco
  description: 'for example: q_auto:eco'
- name: product_type
  type: tag_list
  default: []
  label: Product Type
pages:
- products/Coastal Adirondack Chair.md
- products/painted-ardirondack-chair-white.md
- products/painted-adirondack-chair-grey.md
- products/painted-adirondack-chair-red.md
- products/painted-ardirondack-chair-blue.md
- products/wooden-2-seater-garden-bench-with-under-seat-storage.md
- products/grey-park-bench-3-seater.md
- products/white-lutyens-garden-bench.md
- products/bench-hadia.md
- products/storage-bench-with-3-baskets.md
- products/2-seater-bench.md
- products/grey-lutyens-garden-bench.md
- products/wooden-bench.md
- products/wicker-cushion-wood-chair.md
